# typed: false
# frozen_string_literal: true

# This file was generated by running `brew tap curogom/curompt` and then `brew create curompt`
class Curompt < Formula
  desc "CLI tool for analyzing, evaluating, and optimizing LLM prompts"
  homepage "https://github.com/curogom/curompt"
  url "https://github.com/curogom/curompt/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "e65941bcf9a6b6f6e628976c346dcc38d92acbef7f51dcf9b7525fa949c4e74d"
  license "Apache-2.0"
  version "1.0.0"
  head "https://github.com/curogom/curompt.git", branch: "main"

  depends_on "go" => :build

  def install
    # Build the binary with version info
    version_str = version.to_s
    build_time = Time.now.utc.strftime("%Y-%m-%d_%H:%M:%S")
    
    # Build ldflags as a single quoted string for -ldflags flag
    # Important: All flags must be in one string passed to -ldflags
    ldflags = [
      "-s",
      "-w",
      "-X main.Version=#{version_str}",
      "-X main.BuildTime=#{build_time}",
      "-X main.GitCommit=#{version_str}"
    ].join(" ")
    
    # Use shell command to ensure ldflags is passed as single quoted string
    # Ruby's system with array splits ldflags by spaces, causing issues
    system("go build -ldflags '#{ldflags}' -o #{bin}/curompt ./cmd/curompt")
  end

  test do
    # Test basic functionality
    system "#{bin}/curompt", "--version"
  end
end
