# typed: false
# frozen_string_literal: true

# This file was generated by running `brew tap curogom/curo-prompt` and then `brew create curo-prompt`
class CuroPrompt < Formula
  desc "CLI tool for analyzing, evaluating, and optimizing LLM prompts"
  homepage "https://github.com/curogom/curo-prompt"
  url "https://github.com/curogom/curo-prompt/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "ac773d2af00ded20ba4b1bad2b9637e203e02180fcd2fa797d0743cfc8c9c80d" # TODO: Calculate SHA256 after first release
  license "Apache-2.0"
  head "https://github.com/curogom/curo-prompt.git", branch: "main"

  depends_on "go" => :build

  def install
    # Build the binary with version info
    ldflags = %W[
      -s -w
      -X main.Version=#{version}
      -X main.BuildTime=#{Time.now.utc.iso8601}
      -X main.GitCommit=#{version}
    ].join(" ")
    
    system "go", "build", "-ldflags", ldflags,
           "-o", bin/"curo-prompt", "./cmd/curo-prompt"
  end

  test do
    # Test basic functionality
    system "#{bin}/curo-prompt", "--version"
  end
end

