# typed: false
# frozen_string_literal: true

# This file was generated by running `brew tap curogom/curo-prompt` and then `brew create curo-prompt`
class CuroPrompt < Formula
  desc "CLI tool for analyzing, evaluating, and optimizing LLM prompts"
  homepage "https://github.com/curogom/curo-prompt"
  url "https://github.com/curogom/curo-prompt/archive/refs/tags/v0.1.1.tar.gz"
  sha256 "db83ed869a533375c41ceaaf04d53f9d73efc64214b3aae1ce3ff9da43e85b9b"
  license "Apache-2.0"
  version "0.1.1"
  head "https://github.com/curogom/curo-prompt.git", branch: "main"

  depends_on "go" => :build

  def install
    # Build the binary with version info
    version_str = version.to_s
    build_time = Time.now.utc.strftime("%Y-%m-%d_%H:%M:%S")
    
    # Build ldflags as a single string for -ldflags flag
    ldflags_str = [
      "-s",
      "-w",
      "-X main.Version=#{version_str}",
      "-X main.BuildTime=#{build_time}",
      "-X main.GitCommit=#{version_str}"
    ].join(" ")
    
    system "go", "build", "-ldflags", ldflags_str,
           "-o", bin/"curo-prompt", "./cmd/curo-prompt"
  end

  test do
    # Test basic functionality
    system "#{bin}/curo-prompt", "--version"
  end
end
